OUTPUT_ROOT: ASNET-COCO
DIST_BACKEND: 'nccl'
WORKERS: 32
DEVICE: cuda
SEED: 42
PI: mAP
CUDNN:
  BENCHMARK: False
  DETERMINISTIC: False
  ENABLED: True
DATASET:
  FILE: coco
  NAME: COCODataset
  ROOT: 'data/coco/'
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]
  # IMG_NUM_PER_GPU: [16,8,4,4,2]
  IMG_NUM_PER_GPU: [16,16,16,16,16]
  SUB_NUM_CLASSES: 1
  OBJ_NUM_CLASSES: 91
  # MAX_SIZE: [1333]
  # SCALES: [[480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800]]
  # MAX_SIZE: [448, 544, 640, 736, 832]
  # SCALES: [[352,384,416],[448, 480, 512],[544,576,608],[640,672,704],[736,768,800]]
  MAX_SIZE: [448, 448, 448, 448, 448]
  SCALES: [[352,384,416],[352,384,416],[352,384,416],[352,384,416],[352,384,416]]
MODEL:
  FILE: asnet_coco_pretrain
  NAME: ASNet
  RESUME_PATH: 'data/detr-r50-e632da11.pth'
BACKBONE:
  NAME: resnet50
  DIALATION: False
TRANSFORMER:
  BRANCH_AGGREGATION: True
  POSITION_EMBEDDING: sine
  HIDDEN_DIM: 256
  ENC_LAYERS: 6
  DEC_LAYERS: 6
  DIM_FEEDFORWARD: 2048
  DROPOUT: [0.1,0.1,0.1,0.1,0.1]
  NHEADS: 8
  NUM_QUERIES: 100
  PRE_NORM: False
  NUM_FEATURE_LEVELS: 4 
  DEC_N_POINTS: 4 
  ENC_N_POINTS: 4 
  WITH_BOX_REFINE: True 
  TWO_STAGE: True 
MATCHER:
  COST_CLASS: 2
  COST_BBOX: 5
  COST_CIOU: 2
LOSS: 
  AUX_LOSS: True
  DICE_LOSS_COEF: 1
  DET_CLS_COEF: [2, 2]
  BBOX_LOSS_COEF: [5, 5]
  CIOU_LOSS_COEF: [2, 2]
  EOS_COEF: 0.1
TRAINER:
  FILE: coco_trainer
  NAME: COCOTrainer
TRAIN:
  LR: 1e-3
  LR_BACKBONE: 1e-4
  LR_LINEAR_PROJ_MULT: 0.1
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0
  LR_DROP: [60,80]
  MAX_EPOCH: 100
  PL_STAGE: [0,10,20,30,40]
  PRINT_FREQ: 20
  SAVE_INTERVAL: 1
  SAVE_EVERY_CHECKPOINT: True
  VAL_WHEN_TRAIN: False
  CLIP_MAX_NORM: 0.1
  RESUME: True
TEST:
  REL_ARRAY_PATH: data/hico/rel_np.npy
  USE_EMB: TRUE
  MODE: hico

#mAP: 0.06947069272176191 mAP rare: 0.026867224023498563  mAP nonrare: 0.0821964041511133  max recall: 0.3400944930953433
