OUTPUT_ROOT: ERNet_hoia
DIST_BACKEND: 'nccl'
WORKERS: 24
DEVICE: cuda
SEED: 42
PI: mAP
CUDNN:
  BENCHMARK: True
  DETERMINISTIC: False
  ENABLED: True
DATASET:
  FILE: hico_det
  NAME: HICODetDataset
  ROOT: '/home/cyphi02/Marcus/ERNet/data/hoia/'
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]
  IMG_NUM_PER_GPU: 3
  SUB_NUM_CLASSES: 1
  OBJ_NUM_CLASSES: 12
  REL_NUM_CLASSES: 10
  MAX_SIZE: 1333
  SCALES: [480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800]
MODEL:
  FILE: hoia_ernet
  NAME: ERNet_HOIA
BACKBONE:
  NAME: tf_efficientnetv2_s.in21k_ft_in1k
  DIALATION: False
  PRETRAINED: True
TRANSFORMER:
  BRANCH_AGGREGATION: True
  POSITION_EMBEDDING: sine
  HIDDEN_DIM: 256
  ENC_LAYERS: 6
  DEC_LAYERS: 6
  DIM_FEEDFORWARD: 1024
  DROPOUT: 0.1
  NHEADS: 8
  NUM_QUERIES: 100
  REL_NUM_QUERIES: 16
  PRE_NORM: False
  NUM_FEATURE_LEVELS: 3
  DEC_N_POINTS: 4
  ENC_N_POINTS: 4
  WITH_BOX_REFINE: True 
  TWO_STAGE: True 
MATCHER:
  COST_CLASS: 1
  COST_BBOX: 5
  COST_CIOU: 2
LOSS: 
  AUX_LOSS: True
  IOU_AWARE: True 
  IOU_AWARE_COEF: 2
  DICE_LOSS_COEF: 1
  REL_CLS_COEF: 1
  DET_CLS_COEF: [1,1]
  BBOX_LOSS_COEF: [5, 5]
  CIOU_LOSS_COEF: [2, 2]
  EOS_COEF: 0.1
TRAINER:
  FILE: hoi_trainer
  NAME: HOITrainer
TRAIN:
  OPTIMIZER: madgrad
  LR: 1e-4
  LR_MIN: 1e-7
  DECAY_RATE: 0.1
  LR_WARMUP: 1e-6
  LR_BACKBONE: 1e-5
  LR_LINEAR_PROJ_MULT: 0.1
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-5
  LR_FACTOR: 0.1
  LR_SCHEDULER: 'CosineLRScheduler'
  WARMUP_INIT_FACTOR: 0.1
  WARMUP_STEP: 5
  WARMUP_EPOCH: 0
  LR_DROP: [60,80]
  MAX_EPOCH: 100
  PL_STAGE: [0,10,20,30,40]
  PRINT_FREQ: 100
  SAVE_INTERVAL: 1
  SAVE_EVERY_CHECKPOINT: True
  VAL_WHEN_TRAIN: False
  CLIP_MAX_NORM: 0.1
  RESUME: False 
TEST:
  REL_ARRAY_PATH: /home/cyphi02/Marcus/ERNet/data/hoia/corre_hoia.npy
  USE_EMB: TRUE
  MODE: hoia
  PUE: False